import { chromium } from 'playwright';
const S = process.argv[2];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => console.log('pageerror:', e.message));
page.on('response', r => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url()); });
await page.goto('http://localhost:8765/', { waitUntil: 'load' });
await page.waitForTimeout(9000);
await page.screenshot({ path: `${S}/i-docked.png` });
await page.mouse.wheel(0, 700); await page.waitForTimeout(500);
const rows = page.locator('.row');
await rows.nth(3).hover(); await page.waitForTimeout(2500);
await page.screenshot({ path: `${S}/i-hover.png` });
await page.mouse.move(700, 450); await page.waitForTimeout(800);
await page.screenshot({ path: `${S}/i-left.png` });
await page.locator('#hackathons').scrollIntoViewIfNeeded(); await page.waitForTimeout(400);
await page.locator('#hackathons .row').nth(1).hover(); await page.waitForTimeout(1200);
await page.screenshot({ path: `${S}/i-hack.png` });
await page.locator('#archive').scrollIntoViewIfNeeded(); await page.waitForTimeout(400);
await page.locator('#archive .arow').nth(0).hover(); await page.waitForTimeout(1800);
await page.screenshot({ path: `${S}/i-archive.png` });
await page.locator('#about').scrollIntoViewIfNeeded(); await page.waitForTimeout(600);
await page.screenshot({ path: `${S}/i-about.png` });
await browser.close();
