// Single source of truth for every project on jerryli.design.
// Every fact here is one Jerry has stated himself. Do not add claims he has not made.
//
// kind:    main | hackathon | concept | object | archive
// draft:   true = waiting on media from Jerry's project folder. Drafts only render in
//          preview builds (PREVIEW=1) and never in production.
// media:   { v: 'videos/x.mp4' } or { i: 'images/x.jpg' }, with a caption.
// preview: hover loop in assets/previews/<slug>.mp4 (built by tools/previews.sh).

export const site = {
  name: 'Jerry Li',
  url: 'https://www.jerryli.design',
  email: 'jerry@jerryli.design',
  linkedin: 'https://www.linkedin.com/in/jerry-li-md/',
  github: 'https://github.com/jerryli08',
  description: 'Jerry Li is a mechanical engineering student at the University of Illinois Urbana-Champaign who designs and builds robots, drones and electric vehicles.',
};

export const projects = [
  // ------------------------------------------------------------------ MAIN
  {
    slug: 'hybrid-vehicle', pinned: true, hero: true, size: 'lg', // the live 3D scene on the landing page
    kind: 'main',
    title: 'Drone on Wheels',
    subtitle: 'Hybrid aerial-ground vehicle',
    short: 'A drone and a ground rover that dock together, so each one can carry the other.',
    org: 'MIT Lincoln Laboratory',
    date: 'Jul to Aug 2025',
    year: '2025',
    role: 'Project lead. Designed and fabricated all hardware',
    team: '7 people',
    tools: ['Fusion 360', '3D printing', 'Linkage design', 'Geartrains', 'Belt drive', 'Servo actuation'],
    stats: [
      { v: 'Co-first author', l: 'Poster at IEEE MIT URTC 2025' },
      { v: '10 DOF', l: 'Latch linkage driven by one servo' },
      { v: '7', l: 'Person team' },
    ],
    body: [
      { h: 'Overview', p: [
        'I came up with this project, recruited the team, and designed and fabricated all of the hardware. It is a cooperative multi-agent system: an aerial vehicle (UAV) with custom landing gear, and a ground vehicle (UGV) with actuated latches that lock onto that gear.',
        'Docked, each vehicle can carry the other. The UGV carries the UAV to save its battery, and the UAV lifts the UGV over terrain it cannot drive across or up to an aerial viewpoint. The target applications are search and rescue and data collection.',
      ]},
      { h: 'The latch', p: [
        'The docking latch is a linkage geartrain with 10 degrees of freedom, 4 passive and 6 active, all driven by a single servo so the mechanism stays light enough to fly.',
      ]},
      { h: 'Research', p: [
        'After the summer we ran more tests, collected more data and wrote the work up. I presented the poster, "Drone on Wheels: A Hybrid UAV-UGV System for Precision Course Navigation", as co-first author at the IEEE MIT Undergraduate Research Technology Conference on October 10 to 12, 2025. SLAM integration was the next step we identified.',
        'Authors: Jerry Li and Mihika Sakharpe (co-first), Zoe Zhao, Katherine Zhang, William Kollmyer, Shashwat Pandya, and Chris Rincon (PI).',
      ]},
    ],
    media: [
      { v: 'videos/hybrid-vehicle-flight.mp4', c: 'The drone carrying the rover' },
      { v: 'videos/hybrid-vehicle-driving.mp4', c: 'The rover carrying the drone' },
      { v: 'videos/hybrid-vehicle-detached.mp4', c: 'Working separately: the drone flies the course while the rover waits' },
    ],
    links: [{ label: 'Research poster (PDF)', href: '/assets/docs/drone-on-wheels-poster.pdf' }],
    cad: 'https://a360.co/45sUzAD',
  },
  {
    slug: 'ftc-decode', featured: 2,
    kind: 'main',
    title: 'FTC DECODE Robot',
    subtitle: 'Team 26115 Alphabots',
    short: 'I designed our first robot, then led a turret shooter for Worlds, where we won the 1st place Sustain Award.',
    org: 'FIRST Tech Challenge',
    date: 'Sep 2025 to May 2026',
    year: '2026',
    role: 'Team captain; designed V1, led the V2 shooter',
    team: 'Alphabots, FTC 26115',
    tools: ['Fusion 360', 'Carbon fiber', 'Turret shooter', 'Odometry aiming', 'Pedro Pathing'],
    stats: [
      { v: '1st place', l: 'Sustain Award, FIRST World Championship' },
      { v: '8,000+', l: 'FTC teams worldwide' },
      { v: '50,000+', l: 'Views on our build content' },
    ],
    body: [
      { h: 'Overview', p: [
        'I captained Alphabots through the 2025-26 DECODE season. I designed our first robot entirely by myself; for the World Championship we put a turret shooter on its chassis that aims from the robot\'s odometry pose. The engineering decisions on the new shooter were mine, and a student who had never used CAD modelled it while I guided him through every step.',
        'At the FIRST World Championship in May 2026 we won the 1st place Sustain Award, which recognizes building a program that outlasts its founders. Our build videos reached more than 50,000 views across Instagram, YouTube and TikTok.',
      ]},
    ],
    media: [
      { v: 'videos/ftc-decode-worlds-match.mp4', c: 'A qualification match in the Jackson Division at the World Championship, from the event broadcast. We are 26115 on the red alliance' },
      { v: 'videos/ftc-decode-turret-tracking.mp4', c: 'The Worlds robot, with its turret shooter, driving on our practice field' },
      { v: 'videos/ftc-decode-intake-testing.mp4', c: 'Loading balls into the robot to test the intake and transfer' },
    ],
  },
  {
    slug: 'frc-rebuilt', pinned: true, featured: 1,
    kind: 'main',
    title: 'FRC REBUILT Robot',
    subtitle: 'Team 2856 Planetary Drive',
    short: 'Designed solo and remotely in my first FRC season: three independent shooters on a swerve drive, 22.0 in tall to drive under the trench. It played in the playoffs at the Smoky Mountains Regional.',
    org: 'FIRST Robotics Competition',
    date: 'Jan to Mar 2026',
    year: '2026',
    role: 'Sole designer, working remotely',
    team: 'Planetary Drive, FRC 2856',
    tools: ['Fusion 360', 'REV MAXSwerve', 'Kraken X60', 'NEO 2.0', 'Waterjet-cut aluminum', 'Polycarbonate'],
    stats: [
      { v: 'Solo', l: 'Robot design' },
      { v: '21 of 46', l: 'Qualification rank' },
      { v: 'Round 2', l: 'Playoffs, 7th alliance' },
    ],
    body: [
      { h: 'Overview', p: [
        'I designed this robot by myself for FRC team 2856, Planetary Drive, for the 2026 game REBUILT. It was my first FRC season, the team had never used CAD, and I worked remotely from Maryland: Fusion 360 links, DXF files, and a machinist in the shop waterjet cut the plates.',
        'At the 2026 Smoky Mountains Regional the team ranked 21st of 46, was picked onto the 7th alliance, and went out in the second round of the playoffs.',
      ]},
    ],
    media: [
      { i: 'images/frc-rebuilt.jpg', c: 'The robot at the 2026 Smoky Mountains Regional' },
    ],
    cad: 'https://a360.co/4lvYOTs',
  },
  {
    slug: 'build-plate-robot', pinned: true, featured: 4,
    kind: 'main',
    title: 'Replac3d',
    subtitle: 'Automatic 3D printer build plate changer',
    short: 'A robot that swaps finished build plates for fresh ones so a 3D printer can run around the clock.',
    org: 'Personal project',
    date: 'Feb to Aug 2024',
    year: '2024',
    role: 'Solo build',
    team: 'Solo',
    tools: ['Fusion 360 + FEA', 'CNC router', 'Arduino Uno', 'TMC2209 drivers', 'AccelStepper', 'Electromagnets'],
    stats: [
      { v: 'Top 12', l: 'of 2,042 projects, Hack Club Arcade' },
      { v: '$300', l: 'Polymaker sponsorship' },
      { v: '24 h', l: 'Printing, up from 7 h a day' },
    ],
    body: [
      { h: 'The problem', p: [
        'My FTC team could only run our 3D printer from 3 to 10 PM, because someone had to be there to pull each finished print. Replac3d removes the finished build plate, sets it aside and loads a fresh one, so the printer can keep going unattended all day and night.',
      ]},
      { h: 'How it works', p: [
        'Two belt-driven telescoping slides carry four electromagnets 355 mm into the printer; they grab the steel build plate from above and pull it out. A belt-driven turntable then swings the arm to park the used plate on one holder and pick up a fresh plate from the other, and the arm loads it into the printer. TMC2209 stepper drivers on my own perfboard run everything from an Arduino Uno.',
      ]},
      { h: 'The hard part', p: [
        'Getting the electromagnets to hold the plate every time. The stock plates were too thin and PEI-coated, so I had my own 3 mm steel plates laser cut, which made pickup 100% reliable.',
      ]},
    ],
    media: [
      { v: '/assets/media/build-plate-robot/full-cycle-4x.mp4', c: 'The complete swap in one take, at 4x speed', tall: true },
      { v: 'videos/replac3d-cncing-plates.mp4', c: 'The aluminum side plates being CNC machined' },
      { i: 'images/replac3d-mid-build.jpg', c: 'Mid-build: steppers on a CNC aluminum mount, stood off from the laser-cut steel base plate' },
      { v: 'videos/replac3d-hand-demo.mp4', c: 'Running the removal and replacement motion by hand' },
      { i: 'images/replac3d-perfboard.jpg', c: 'Custom perfboard: two TMC2209 stepper drivers on an Arduino Uno' },
      { v: 'videos/replac3d-auto-test.mp4', c: 'Automated test of the turntable and extension', tall: true },
      { v: 'videos/replac3d-drag-chain.mp4', c: 'Drag chain cable management test', tall: true },
      { i: 'images/replac3d-finished.jpg', c: 'The finished robot' },
    ],
    links: [{ label: 'Code on GitHub', href: 'https://github.com/jerryli08/replac3d' }],
    cad: 'https://a360.co/47cTdf9',
  },
  {
    slug: 'electric-vehicle', size: 'wide',
    kind: 'main',
    title: 'Science Olympiad Electric Vehicle',
    subtitle: '2024-25 Electric Vehicle event',
    short: 'A precision-stopping race car that took 1st at regionals and 2nd of 72 at the UPenn Invitational.',
    org: 'Science Olympiad',
    date: 'Sep 2024 to Jan 2025',
    year: '2025',
    role: 'Designed and built solo. My partner helped test',
    team: 'Solo build',
    tools: ['Fusion 360 FEA', 'G10 fiberglass', 'BLDC motor', 'MT6701 encoder', 'Arduino Nano', 'BLHeli_32', 'GT2 belts', '3D-printed gears'],
    stats: [
      { v: '1st of 48', l: 'East Maryland Regional' },
      { v: '2nd of 72', l: 'UPenn Invitational' },
      { v: '73%', l: 'Lighter chassis plates' },
    ],
    body: [
      { h: 'Overview', p: [
        'I designed and built this car by myself for the 2024-25 Science Olympiad Electric Vehicle event, which scores a car on how quickly it covers a set distance and how close to the target it stops. It is a 30 by 60 cm all-wheel-drive car that covered 8.3 m in 2.97 s and stopped 1.1 cm (0.13%) from the target.',
      ]},
      { h: 'Iteration', p: [
        'Version one used CNC-cut HDF plates. They were heavy, and too stiff: I knew the chassis needed to flex over floor bumps. For version two I used Fusion 360 FEA to design a lattice into 1.5 mm G10 fiberglass plates that gives the chassis torsional flexibility, so the car passively absorbs bumps in the floor.',
        'The two main plates went from 738 g to 198 g, 73% lighter, and the run time dropped from about 15 s to 2.9 s.',
      ]},
      { h: 'Electronics', p: [
        'An Arduino Nano reads an MT6701 magnetic absolute encoder over I2C and drives the brushless motor\'s ESC with PWM. The ESC is tuned in BLHeli_32 Suite.',
      ]},
      { h: 'Results', p: [
        '1st of 48 at the East Maryland Regional, 2nd of 28 at the Maryland State Championship, 2nd of 72 at the UPenn Invitational (behind the team that went on to win nationals), and 4th of 57 at the Princeton Invitational.',
      ]},
    ],
    media: [
      { v: 'videos/sciolyev-home-test.mp4', c: 'Early test at home, real time', tall: true },
      { v: 'videos/sciolyev-school-test.mp4', c: 'Testing at school', tall: true },
      { i: 'images/electric-vehicle.jpg', c: 'The finished car' },
      { v: 'videos/sciolyev-motor-test.mp4', c: 'Integrated test of the brushless motor and MT6701 encoder', tall: true },
      { v: 'videos/sciolyev-v1-test.mp4', c: 'First ground test on the HDF plates: too heavy, and the ESC was not tuned yet', tall: true },
      { i: 'images/sciolyev-v2-mid-build.jpg', c: 'Mid-rebuild with the 1.5 mm G10 fiberglass plates' },
    ],
    links: [{ label: 'Code on GitHub', href: 'https://github.com/jerryli08/sciolyEv' }],
    cad: 'https://a360.co/4o6t1bB',
  },
  {
    slug: 'electric-vehicle-2026',
    kind: 'main',
    title: 'Science Olympiad Electric Vehicle 2026',
    subtitle: '2025-26 Electric Vehicle event',
    short: 'A steered car for the 2025-26 Electric Vehicle event: two versions, from servo steering to a digital caliper and linkage that sets the steering angle in 0.01 mm steps.',
    org: 'Science Olympiad',
    date: 'Sep 2025 to Mar 2026',
    year: '2026',
    role: 'Designed both versions and wrote the code',
    tools: ['Fusion 360', 'Arduino Nano Every', 'MT6701 encoder', 'Brushless motor', 'Digital caliper', '2020 aluminum extrusion', '3D printing'],
    stats: [
      { v: '2', l: 'Versions: servo, then caliper steering' },
      { v: 'Under 1 day', l: 'To design version 1' },
      { v: '142 to 452 mm', l: 'Wheelbase, version 1 to version 2' },
    ],
    body: [{ h: 'Overview', p: [
      'My car for the 2025-26 Science Olympiad Electric Vehicle event, the season after my first electric vehicle. The rules added a bonus for driving between two cans about a meter off the straight line, so the car has to drive a precise curve.',
      'I designed version 1 in less than a day, with a servo steering the front wheel; the backlash in the servo made the steering horribly inaccurate. Version 2 steers with a digital caliper and a linkage, which set the steering angle quite precisely. Its linkage bar was 3D printed, so it was not that accurate, but it was still way better than the servo.',
    ] }],
    links: [
      { label: 'Code on GitHub', href: 'https://github.com/jerryli08/sciolyev2026' },
      { label: 'See the 2024-25 car', href: '/projects/electric-vehicle' },
    ],
    media: [{ i: 'images/electric-vehicle-2026/still-v2-at-cans.webp', c: 'Version 2 at the can line during a competition run' }],
  },
  {
    slug: 'scioly-machines',
    kind: 'main',
    title: 'Science Olympiad Machines',
    subtitle: '2025-26 Machines event',
    short: 'A compound lever that measures mass ratios: a class 1 lever joined to a class 2 lever by a rigid link.',
    org: 'Science Olympiad',
    date: 'Sep 2025 to Mar 2026',
    year: '2026',
    tools: ['2020 aluminum extrusion', '3D printing', 'Ball bearings', 'Compound levers'],
    body: [{ h: 'Overview', p: [
      'My build for the 2025-26 Science Olympiad Machines event, where you are given test masses and have to find the ratios between them.',
      'A class 1 lever is joined to a class 2 lever by a rigid link. The link arms are 75 mm and 375 mm in the CAD, so the link gives 5 : 1 and the mass ratio is b / (5a), where a and b are the two masses\' distances from their fulcrums. Built from 2020 aluminum extrusion, 3D-printed mounts and a ball bearing at every pivot.',
    ] }],
    media: [{ i: 'images/scioly-machines/still-device-full.webp', c: 'The whole device: two beams on two posts, with the link at the right end' }],
  },
  {
    slug: 'electric-bike', pinned: true, featured: 3,
    kind: 'main',
    title: 'Electric Bike',
    subtitle: '5.3 kW mid-drive conversion',
    short: 'A standard bicycle converted into a 5.3 kW mid-drive e-bike, with every custom part designed by me.',
    org: 'Personal project',
    date: 'Jun to Aug 2025',
    year: '2025',
    role: 'Solo build',
    team: 'Solo',
    tools: ['Fusion 360', 'Sheet metal design', '5052 aluminum', 'Carbon fiber', 'VESC Tool', '3D printing (FDM)'],
    stats: [
      { v: '5.3 kW', l: 'Mid-drive' },
      { v: '100 N·m', l: 'At the output sprocket' },
      { v: 'About 35 mph', l: 'About 20 miles of range' },
      { v: 'Solo', l: 'Design and build' },
    ],
    body: [
      { h: 'Overview', p: [
        'I converted a 2019 Trek Dual Sport 2 into a 5.3 kW mid-drive electric bike for my mom. Two 2.6 kW SKP 6465 motors (150 KV) share one serpentine belt, and two belt stages (16.2 : 1 overall) on two jackshaft axles bring the drive to a 20-tooth sprocket that drives the bike\'s own chain with 100 N·m of torque. It does about 35 mph with about 20 miles of range on a 48 V pack and a VESC controller.',
        'I designed all of the custom parts. The brackets and outer plates are laser cut from 5052 aluminum and powder coated, with the brackets bent on a press brake, the carbon fiber plates were cut by an outside shop, one adapter plate is stainless steel, and I 3D printed the spacers and the idler mount. The cranks freewheel, so the pedals stay still under power.',
      ]},
    ],
    media: [
      { v: 'videos/ebike-riding.mp4', c: 'Riding' },
      { v: 'videos/ebike-outside-walkaround.mp4', c: 'Walkaround' },
      { v: 'videos/ebike-close-up.mp4', c: 'Close-up on the belt reductions' },
      { i: 'images/ebike-nondrive-side.jpg', c: 'Non-drive side' },
      { v: 'videos/ebike-max-speed.mp4', c: 'Max speed test, with the cranks freewheeling' },
      { i: 'images/ebike-parts.jpg', c: 'Custom parts: carbon fiber plates and bent, powder-coated 5052 aluminum' },
      { i: 'images/ebike-build-progress.jpg', c: 'Mid-build: the drive unit in the frame, with the first version\'s two jockey wheels' },
      { i: 'images/ebike-vesc-config.jpg', c: 'Configuring the throttle in VESC Tool' },
    ],
    cad: 'https://a360.co/45BrfHR',
  },
  {
    slug: 'ftc-into-the-deep',
    kind: 'main',
    title: 'FTC INTO THE DEEP Robot',
    subtitle: 'Team 18996 S.T.A.T.I.C.',
    short: 'I cut our horizontal extension from 15 in to 3 in wide while the intake went through five versions, in our most successful S.T.A.T.I.C. season: 1st place Think Award at regionals.',
    org: 'FIRST Tech Challenge',
    date: 'Sep 2024 to Mar 2025',
    year: '2025',
    role: 'Team captain',
    team: 'S.T.A.T.I.C., FTC 18996',
    tools: ['Fusion 360', '3D printing', 'goBILDA', 'Linear slides', 'Cable carrier'],
    stats: [
      { v: '1st place', l: 'Think Award, FIRST Chesapeake Regionals' },
      { v: 'Semifinalist', l: 'Division playoffs' },
    ],
    body: [
      { h: 'Overview', p: [
        'The 2024-25 season was S.T.A.T.I.C.\'s most successful. We won the 1st place Think Award, which recognizes the engineering design process, at the FIRST Chesapeake Regionals, and made the division semifinals.',
      ]},
    ],
    media: [
      { v: 'ftc-into-the-deep/hero-final-intake-real-field.mp4', c: 'The final robot on a practice field at the FIRST Chesapeake Championship, March 2025' },
    ],
  },
  {
    slug: 'autonomous-drone-racing',
    kind: 'main',
    title: 'Autonomous Drone Racing',
    subtitle: 'Capstone race winner',
    short: 'Led a team of five writing vision-guided autonomy for a race drone. We won the capstone race in 52 s, under half the second-best team’s time.',
    org: 'MIT Department of Aeronautics and Astronautics',
    date: 'Jul to Aug 2025',
    year: '2025',
    role: 'Autonomous systems engineering intern',
    team: 'Team of 5, which I led',
    tools: ['Python (asyncio)', 'OpenCV', 'NumPy', 'Picamera2', 'MAVSDK', 'MAVLink', 'Raspberry Pi 5', 'ROS 2'],
    stats: [
      { v: '1st of 5', l: 'Capstone autonomous drone race' },
      { v: '52 s', l: 'Under half the second-best team’s time' },
    ],
    body: [
      { h: 'Overview', p: [
        'I led a team of five writing the software for a Holybro X500 quadcopter in an autonomous drone race: follow an LED line on the floor, past hoops with AprilTags on them, with nobody flying it. A downward camera finds the line in every frame with color segmentation and a least-squares line fit on a Raspberry Pi 5, and a forward camera is for obstacle avoidance.',
        'We won the race in 52 seconds, less than half the second-best team’s time, and we were the only team to take off autonomously and complete the whole course in one run.',
      ]},
    ],
    media: [{ i: 'images/autonomous-drone-racing/still-drone-over-rope.webp', c: 'On the LED line in the flight cage' }],
  },
  {
    slug: 'pen-plotter',
    kind: 'main',
    title: '5-Bar Pen Plotter',
    subtitle: 'Parallel robot with inverse kinematics',
    short: 'A 5-bar parallel robot that draws from Cartesian coordinates, built to learn the linear algebra behind robot arms.',
    org: 'Personal project',
    date: 'May to Jun 2025',
    year: '2025',
    role: 'Solo build',
    team: 'Solo',
    tools: ['Inverse kinematics', 'C++', 'Arduino Nano', 'AccelStepper', 'NEMA 17', 'TMC2209', 'Fusion 360', '3D printing'],
    links: [{ label: 'Code on GitHub', href: 'https://github.com/jerryli08/5bar' }],
    stats: [
      { v: '2', l: 'NEMA 17 steppers' },
      { v: 'IK', l: 'Cartesian to joint angles' },
    ],
    body: [
      { h: 'Overview', p: [
        'I built a 5-bar pen plotter to learn how linear algebra and transformation matrices apply in robotics. The 3D-printed arms are driven by two NEMA 17 steppers, each on a TMC2209 driver, programmed in C++ on an Arduino Nano.',
        'You give it Cartesian coordinates and inverse kinematics turns them into target angles for the two motors.',
      ]},
    ],
    media: [
      { v: 'videos/pen-plotter-jerryli.mp4', c: 'Writing "Jerry Li" from Cartesian coordinates' },
      { v: 'videos/pen-plotter-square.mp4', c: 'Drawing a square' },
    ],
    cad: 'https://a360.co/46NPB1S',
  },
  {
    slug: 'steam-carnival-robot',
    kind: 'main',
    draft: true,
    title: 'STEAM Carnival Pitching Robot',
    subtitle: 'Telescoping pitching arm',
    short: 'An FTC robot with a telescoping pitching arm, built in 4 days for the HoCo STEAM Carnival.',
    org: 'Howard County Library System',
    date: 'Jul to Aug 2024',
    year: '2024',
    role: 'STEM instructor and youth peer intern',
    tools: ['Proportional control', 'Cosine feedforward'],
    stats: [{ v: '4 days', l: 'Design to working robot' }],
    body: [
      { h: 'Overview', p: [
        'As a STEM instructor at the Howard County Library System, I built an FTC robot with a telescoping pitching arm in 4 days for the HoCo STEAM Carnival. The arm runs a proportional controller with cosine feedforward. I also wrote and taught a robotics curriculum.',
      ]},
    ],
    media: [],
  },
  {
    slug: 'battlebot',
    kind: 'main',
    title: '1 lb Combat Robot',
    subtitle: 'Plastic antweight horizontal spinner',
    short: 'A 1 lb antweight combat robot designed and built in 4 days for MACRO\'s Ides of July event.',
    org: 'MACRO',
    date: 'Jul 2024',
    year: '2024',
    role: 'Solo build',
    team: 'Solo',
    tools: ['Fusion 360', '3D printing', 'TPU', 'Brushless weapon motor', 'DC gearmotor drive'],
    links: [{ label: 'CAD history on GitHub', href: 'https://github.com/jerryli08/antweight' }],
    stats: [
      { v: '4 days', l: 'Design to competition' },
      { v: '1 lb', l: 'Antweight plastic class' },
    ],
    body: [
      { h: 'Overview', p: [
        'In 4 days I designed and built a 1 lb plastic antweight combat robot. It competed at the Ides of July event hosted by MACRO, the Maryland Area Combat Robotics Organization.',
      ]},
    ],
    media: [
      { v: 'battlebot/hero-table-spin.mp4', c: 'Finished: weapon spinning, then turning in place on a table' },
      { i: 'images/battlebot-weighing.jpg', c: 'Weigh-in: 15.5 oz with the battery on the scale' },
      { i: 'battlebot/finished-front.webp', c: 'The finished robot' },
    ],
    cad: 'https://a360.co/3VZaphB',
  },
  {
    slug: 'powerplay-offseason',
    kind: 'main',
    draft: true,
    title: 'PowerPlay Off-Season Robot',
    subtitle: 'My first CAD-designed robot',
    short: 'The off-season robot I built after PowerPlay, and the first robot I ever designed in CAD.',
    org: 'FIRST Tech Challenge',
    date: '2023',
    year: '2023',
    team: 'S.T.A.T.I.C., FTC 18996',
    body: [
      { h: 'Overview', p: ['The first robot I designed in CAD, built in the off-season after the 2022-23 PowerPlay season.'] },
    ],
    media: [],
  },

  // ------------------------------------------------------------------ HACKATHONS
  {
    slug: 'morph', size: 'wide',
    kind: 'hackathon',
    title: 'Morph',
    subtitle: 'Self-folding robot',
    short: 'A chain of 17 cubes that folds itself into one of 88 shapes when you text it.',
    event: 'Hack the North 2026',
    hours: '36 h',
    place: 'Top 30 of 1,000+',
    date: 'Sep 2026',
    year: '2026',
    team: 'Daniel Ganjali, Aydan Ling, Justin Rui and me',
    role: 'Built the text-to-motion software; soldered the motor driver breakout boards',
    tools: ['iMessage via Linq API', 'MiniLM-L6-v2 (int8 ONNX)', 'GPT-4o-mini', 'Best-first fold search', 'MuJoCo', 'Feetech STS3215'],
    stats: [
      { v: 'Top 30', l: 'of 1,000+ hackers' },
      { v: '17', l: 'Cubes, 16 joints that change the shape' },
      { v: '88', l: 'Playable shapes' },
    ],
    body: [
      { h: 'Overview', p: [
        'Morph is a chain of 17 cubes, each cut across its body diagonal, that folds itself into a shape when you text it what you want. The joint in the tip cube never changes the shape, so 16 joints matter: 3^16 = 43,046,721 joint words. I built the path from text to motion: iMessage in through the Linq API, a local MiniLM-L6-v2 classifier with GPT-4o-mini as a fallback, torque limits on the fold plans, the servo executor and MuJoCo validation. I also spent 8 hours soldering USB-C breakout boards for the motor controller drivers.',
        'About 8,000 candidate drawings, generated with Claude, were screened for ones this chain can thread and a judge can name; 88 were playable at the booth, each a planned, checked sequence of single-joint moves.',
      ]},
    ],
    links: [{ label: 'Demo video', href: 'https://lnkd.in/gSRzEcxE' }, { label: 'Code on GitHub', href: 'https://github.com/AydanLing/Hack-The-North' }],
    media: [],
  },
  {
    slug: 'golden-retriever', size: 'wide',
    kind: 'hackathon',
    title: 'Golden Retriever',
    subtitle: 'Assistive fetch robot',
    short: 'Text it what you need and it drives over, grabs it with a learned grasp, and brings it back.',
    event: 'Corgi Hackathon, San Francisco',
    hours: '10.5 h',
    place: '2nd of 250+ teams',
    date: 'Jul 2026',
    year: '2026',
    team: 'Tarun Malarvasan, Ryker Kollmyer, Andrew Wang and me',
    tools: ['SO-101 arm', 'ACT imitation learning', 'Monocular depth', 'HSV detection', 'Axon MAX servos', 'iMessage (Photon)', 'Claude'],
    links: [{ label: 'Code on GitHub', href: 'https://github.com/jerryli08/corgi-hackathon' }],
    stats: [
      { v: '2nd', l: 'of 250+ teams, 1,500+ hackers' },
      { v: '10.5 h', l: 'Build time' },
    ],
    body: [
      { h: 'Overview', p: [
        'An assistive fetch robot for people with limited leg mobility, built by four of us in 10.5 hours. You text it over iMessage and Claude works out which item you want; the robot drives to the shelf using monocular depth estimation and path planning, finds the item with a low side webcam, and grasps it with an SO-101 arm running an ACT policy we trained on about 40 demonstrations. The whole loop worked end to end at judging.',
        'I did all of the soldering, including the Arduino Mega 2560 Pro that drives the two Axon MAX wheel servos.',
      ]},
    ],
    media: [
      { i: 'images/golden-retriever/still-grasp-closed.webp', c: 'Jaws closed on the pill bottle' },
      { i: 'images/golden-retriever/still-overhead-at-shelf.webp', c: 'Parked alongside the shelf with the bottle beside the arm' },
    ],
  },
  {
    slug: 'linqbot',
    kind: 'hackathon',
    title: 'LinqBot',
    subtitle: 'Robot arm with three control modes',
    short: 'An SO-101 arm you can run on its own, drive with your hand through AR glasses, or text over iMessage.',
    event: 'YC Startup School Hackathon',
    hours: '6.5 h',
    date: 'Jul 2026',
    year: '2026',
    team: 'Team of 5',
    tools: ['SO-101 arm', 'Python', 'MediaPipe hand tracking', 'Inverse kinematics (ikpy)', 'Xreal One Pro AR glasses', 'iMessage (Linq)', 'FastAPI'],
    links: [{ label: 'Code on GitHub', href: 'https://github.com/amzoeee/soma-hackathon' }],
    stats: [
      { v: '6.5 h', l: 'Hackathon' },
      { v: '3', l: 'Control modes' },
    ],
    body: [
      { h: 'Overview', p: [
        'Built at the YC Startup School hackathon at Soma Capital by a team of five. An SO-101 arm with three control modes: autonomous pick and place of a can; hand control through the camera on a pair of Xreal One Pro AR glasses, with MediaPipe hand tracking, a fist clutch and pinch-to-close driving the arm through inverse kinematics; and plain-language texts over iMessage, planned into robot tool calls by a language model and clamped to a safe workspace before any servo moves. All three ran on the real arm on the day.',
      ]},
    ],
    media: [
      { i: 'images/linqbot/still-autonomous-grasp.webp', c: 'From above: the jaw closes on the can' },
      { i: 'images/linqbot/still-eye-feed-on-laptop.webp', c: 'The laptop shows what the glasses\u2019 camera sees: a grey image with the operator\u2019s hand in it' },
    ],
  },
  {
    slug: 'braille-printer',
    kind: 'hackathon',
    title: 'Braille Printer',
    subtitle: 'Low-cost gantry prototype',
    short: 'A low-cost braille printer prototype built on a 2020 extrusion gantry.',
    event: 'PennApps XXV',
    hours: '36 h',
    date: 'Sep 2024',
    year: '2024',
    role: 'Designed the gantry; rigged its Y axis with dental floss',
    team: 'Brandon Jeon, Jacob Zhang, Oliver Leung and me',
    tools: ['Fusion 360', '2020 extrusion', 'Stepper motors', 'GT2 timing belt', 'Dental floss', 'Servo', '3D printing'],
    stats: [{ v: '36 h', l: 'Build time' }, { v: '4', l: 'Teammates' }],
    body: [
      { h: 'Overview', p: [
        'In 36 hours at PennApps XXV, my team of four built a prototype braille printer. I designed the gantry: 2020 aluminum extrusion with stepper-driven X and Y axes. The X axis runs on a GT2 timing belt; we ran out of belt for the Y axis, so I rigged it with dental floss wound on a spool on each Y motor.',
      ]},
    ],
    media: [
      { v: '/assets/media/braille-printer/hero-finished-machine.mp4', c: 'The prototype on Sunday morning: the gantry beam, the red servo on its carriage and paper under the frame', tall: true },
    ],
    cad: 'https://a360.co/46GrzqS',
  },

  // ------------------------------------------------------------------ CONCEPTS
  {
    slug: 'manure-drone',
    kind: 'concept',
    draft: false,
    title: 'Manure-Collecting Drone',
    short: 'A drone concept that vacuums up cow manure to cut methane emissions in cattle-farming regions.',
    org: 'Constellation Youth Energy Summit',
    date: 'Summer 2024',
    year: '2024',
    role: 'Came up with the idea. Modified an open spraying drone model in CAD: vacuum canister, intake nozzle and duct, landing gear',
    tools: ['Fusion 360', 'CAD'],
    body: [{ h: 'Overview', p: [
      'A drone concept that vacuums up cow manure, reducing methane emissions in rural agricultural areas with a lot of cattle farming. Designed for the Constellation Youth Energy Summit in summer 2024, for our team\'s climate action plan for a small rural town in New York State.',
      'I built it in CAD on an open GrabCAD model of an EFT agricultural spraying drone: I replaced its spray tank with a vacuum canister, added an intake nozzle and duct, and changed the landing gear.',
    ] }],
    links: [
      { label: 'CAD on GitHub', href: 'https://github.com/jerryli08/cegyes2024' },
      { label: 'Base model: EFT spraying drone (GrabCAD)', href: 'https://grabcad.com/library/eft-spraying-drone-1' },
    ],
    media: [{ i: 'manure-drone/cad-hero.webp', c: 'My CAD of the manure drone: the vacuum canister through the middle of the body, six arms of coaxial motor pairs and 23 in props' }],
  },
  {
    slug: 'drone-arm',
    kind: 'concept',
    title: 'Drone Grabber Arm',
    short: 'A robotic arm under a drone for grabbing household objects, for example in senior homes.',
    org: 'MIT Lincoln Laboratory',
    date: 'Jul 2025',
    year: '2025',
    role: 'Came up with the idea. Designed the arm in CAD and built it',
    team: 'Same team as Drone on Wheels',
    tools: ['CAD', '3D printing', 'Servo joints', 'Carbon fiber links', 'Inverse kinematics (planned)'],
    body: [{ h: 'Overview', p: [
      'A robotic arm under a drone for grabbing household objects, like a bottle of water off a table, for example in a senior home. It was an extra project from the same MIT Lincoln Laboratory team that went on to build Drone on Wheels.',
      'I designed it in CAD and built the whole arm: two servo joints driving the links directly, links made from spare carbon fiber drone arms, and a 3D-printed claw. It was almost ready to go on the drone when we pivoted.',
    ] }],
    links: [{ label: 'See Drone on Wheels', href: '/projects/hybrid-vehicle' }],
    media: [{ i: 'images/drone-arm/arm-assembled.webp', c: 'The arm assembled: shoulder mount and servo, the first carbon link, the elbow and the second link' }],
  },
  {
    slug: 'ftc-decode-two-sided',
    kind: 'concept',
    draft: false,
    title: 'FTC DECODE Two-Sided Intake',
    subtitle: 'Robot concept for the 2025-26 DECODE game',
    short: 'An FTC DECODE robot concept that intakes from both sides, three balls wide on either side.',
    org: 'FIRST Tech Challenge',
    date: 'Feb to Mar 2026',
    year: '2026',
    tools: ['Fusion 360', 'Differential gearing', 'GT2 belt drives', 'Linkage design', 'goBILDA'],
    body: [{ h: 'Overview', p: [
      'A robot concept for the 2025-26 FTC DECODE game that can intake from either side of the robot, three balls wide on each side. One 4-bar linkage swings out to either side and comes back to the middle to hand the balls up to a turret shooter, and two motors run both the 4-bar and its rollers through a differential power take-off.',
      'It was never built: the design was not finished and the World Championship deadline was close, so we built a simpler design from the robot we already had. We did build a test chassis for its drivetrain, four mecanum wheels in a line down the middle.',
    ] }],
    links: [{ label: 'See the FTC DECODE robot', href: '/projects/ftc-decode' }],
    media: [
      { i: 'ftc-decode-two-sided/cad-pto-gearbox-top.webp', c: 'The intake gearbox in the CAD: two motors over a bevel differential, between carbon fiber plates' },
      { i: 'ftc-decode-two-sided/test-chassis-frame.webp', c: 'The drivetrain test chassis going together: a pair of mecanum wheels in the middle of the frame' },
    ],
  },
  {
    slug: 'vtol-tailsitter',
    kind: 'concept',
    title: 'VTOL Tailsitter',
    subtitle: 'Designed in SolidWorks',
    short: 'A tailsitter VTOL aircraft I designed to learn SolidWorks, based on an MIT tailsitter.',
    org: 'Concept',
    date: '',
    year: '',
    tools: ['SolidWorks', 'Multi-body part design', 'Brushless outrunners', 'DALPROP T3045 props'],
    body: [{ h: 'Overview', p: ['I designed this tailsitter to learn SolidWorks. It is based on a tailsitter aircraft from MIT.'] }],
    links: [
      { label: 'CAD on GitHub', href: 'https://github.com/jerryli08/tailsitter' },
      { label: 'The MIT tailsitter', href: 'https://news.mit.edu/2023/planning-algorithm-tailsitter-aircraft-0823' },
    ],
    media: [],
  },
  {
    slug: 'cryptic-extendo',
    kind: 'concept',
    draft: false,
    title: 'Horizontal Extension Intake for Cryptic',
    subtitle: 'FTC CENTERSTAGE, 2023-24',
    short: 'A horizontal extension intake I designed for team Cryptic after they advanced to Worlds.',
    org: 'FIRST Tech Challenge',
    date: '2024',
    year: '2024',
    body: [{ h: 'Overview', p: [
      'After my FTC season ended and Cryptic advanced to the World Championship, I proposed a horizontal extension intake for them, since it was a clear edge that year, and designed it.',
      'They did not use it: they chose to improve other parts of their robot, mainly its reliability.',
    ] }],
    tools: ['Fusion 360', 'Linear slides', 'Roller intakes', 'goBILDA'],
    media: [{ i: 'cryptic-extendo/hero-cad.webp', c: 'The extension intake fully out, rendered from my CAD: a two-stage slide on each side carries it about a metre past the front of the robot' }],
  },
  {
    slug: 'ftc-field-cnc',
    kind: 'concept',
    draft: false,
    title: 'Upcycled CNC Router',
    short: 'A benchtop CNC router gantry designed to be built from the aluminum extrusion of the CENTERSTAGE FTC game field.',
    org: 'Concept',
    date: '',
    year: '',
    tools: ['Fusion 360', 'SFU1605 ball screws', 'HIWIN HGH15 linear rails', 'NEMA 23 steppers'],
    body: [{ h: 'Overview', p: [
      'A benchtop CNC router I designed to be made out of the aluminum extrusions from the CENTERSTAGE FTC game field: six 2 ft lengths of 1 x 1 in extrusion make the frame. The gantry rides on two profile rails, pushed by two ball screws with a stepper motor each, and the carriage runs along the gantry on two more rails and a third ball screw.',
      'I did not build it: I got busy, and I realized I would not have a use for a CNC soon because I was going to college in a year.',
    ] }],
    media: [{ i: 'ftc-field-cnc/cad-hero.webp', c: 'My CAD of the router: the field extrusion frame, the Y rails and ball screws along both sides, and the gantry with the X axis' }],
  },

  // ------------------------------------------------------------------ 3D MODELS
  { slug: 'voronoi-face', kind: 'object', draft: true, title: 'Voronoi Face', short: 'A face sculpted as a Voronoi lattice.', year: '', media: [] },
  { slug: 'hex-napkin-holder', kind: 'object', draft: true, title: 'Hexagonal Napkin Holder', short: 'A 3D-printed hexagonal napkin holder.', year: '', media: [] },

  // ------------------------------------------------------------------ ARCHIVE
  {
    slug: 'ftc-centerstage',
    kind: 'main',
    title: 'FTC CENTERSTAGE Robot',
    short: 'Our first season with CAD. I was overly ambitious with the design, and the robot came together over the season: 0-5 at our first two events, 3-2 at the last two.',
    org: 'S.T.A.T.I.C., FTC 18996',
    date: 'Sep 2023 to Feb 2024',
    year: '2024',
    body: [{ h: 'Overview', p: ['The 2023-24 season was our first with CAD. I was overly ambitious with the design, and the robot came together over the season: we went 0-5 at our first two events, then 3-2 at the last two, with the Inspire Award 2nd Place at the Laurel 2 Qualifier.'] }],
    media: [{ v: 'videos/ftc-2024.mp4', c: 'The 2023-24 robot', tall: true }],
    links: [
      { label: 'Code on GitHub', href: 'https://github.com/CMP-18996/STATIC-CENTERSTAGE' },
      { label: 'Official results', href: 'https://ftc-events.firstinspires.org/2023/team/18996' },
    ],
  },
  {
    slug: 'ftc-powerplay',
    kind: 'archive',
    title: 'FTC POWERPLAY Robot',
    short: 'My first season as captain, and the team\'s first time advancing to regionals.',
    org: 'S.T.A.T.I.C., FTC 18996',
    date: 'Sep 2022 to Feb 2023',
    year: '2023',
    body: [{ h: 'Overview', p: ['2022-23 was my first season as captain and our first year advancing to regionals.'] }],
    media: [{ v: 'videos/ftc-2023.mp4', c: 'The 2022-23 robot' }],
  },
  {
    slug: 'robot-tour',
    kind: 'main',
    title: 'Science Olympiad Robot Tour',
    short: 'A navigation robot on an optical flow sensor, and a lesson in accumulated drift.',
    org: 'Science Olympiad',
    role: 'Solo build',
    date: 'Dec 2024 to Apr 2025',
    year: '2025',
    tools: ['Fusion 360', '3D printing (FDM)', 'Arduino Mega (C++)', 'SparkFun OTOS', 'Axon MINI servos', 'Spur gears', 'GT2 belts'],
    body: [{ h: 'Overview', p: [
      'I built this robot by myself for the 2024-25 Science Olympiad Robot Tour event.',
      'It navigated with an optical tracking odometry sensor (SparkFun OTOS), which was not accurate enough: it drifted over time, and the accumulated error pulled the robot\'s position estimate away from where it actually was.',
    ] }],
    media: [{ v: 'videos/robot-tour.mp4', c: 'Robot Tour navigation run', tall: true }],
    links: [{ label: 'Code on GitHub', href: 'https://github.com/jerryli08/sciolyRoTo' }],
    cad: 'https://a360.co/4pWI35v',
  },
  {
    slug: 'mt-shirt',
    kind: 'main',
    title: 'Monkeytype Shirt',
    short: 'A shirt I designed for Monkeytype, sold on their official store.',
    org: 'Monkeytype',
    date: 'May to Jun 2025',
    year: '2025',
    body: [{ h: 'Overview', p: ['I designed a shirt for Monkeytype, a typing test website with more than 13 million visits a month. It is sold on the official Monkeytype store.'] }],
    media: [
      { i: 'images/mt-shirt.jpg', c: 'The shirt' },
      { i: 'images/mt-shirt-store.jpg', c: 'On the Monkeytype store' },
    ],
    links: [{ label: 'Monkeytype store', href: 'https://monkeytype.store/products/deconstructed-t-shirt-printed' }],
    cad: 'https://a360.co/3Lh6xqg',
  },
  {
    slug: 'bike-odometer',
    kind: 'main',
    title: 'Exercise Bike Odometer',
    short: 'An odometer for my family\'s stationary bike, built in a 12-hour, one-day challenge.',
    org: 'Personal project',
    date: 'Jun 2025',
    year: '2025',
    body: [{ h: 'Overview', p: ['I made an odometer for my family\'s stationary bike. To challenge myself I gave myself one day, and finished in 12 hours.'] }],
    media: [{ v: 'videos/bike-odometer.mp4', c: 'Demo' }],
    cad: 'https://a360.co/4gWhdq9',
  },
  {
    slug: 'ftc-freight-frenzy',
    kind: 'archive',
    title: 'FTC FREIGHT FRENZY Robot',
    short: 'The 2021-22 robot. It was not finished in time to compete.',
    org: 'S.T.A.T.I.C., FTC 18996',
    date: 'Sep 2021 to Jan 2022',
    year: '2022',
    body: [{ h: 'Overview', p: ['The 2021-22 robot. Unfortunately it was not finished in time, so we did not compete that season.'] }],
    media: [{ v: 'videos/ftc-2022.mp4', c: 'The 2021-22 robot' }],
  },
  {
    slug: 'ftc-ultimate-goal',
    kind: 'archive',
    title: 'FTC ULTIMATE GOAL Robot',
    short: 'My first FTC season. I was the team\'s only programmer.',
    org: 'S.T.A.T.I.C., FTC 18996',
    date: 'Sep 2020 to Jan 2021',
    year: '2021',
    body: [{ h: 'Overview', p: ['2020-21 was my first year in FTC, and I was the only programmer on the team.'] }],
    media: [{ v: 'videos/ftc-2021.mp4', c: 'The 2020-21 robot' }],
  },
  {
    slug: 'cty-2023',
    kind: 'archive',
    draft: true,
    title: 'Breadboard Game Console',
    subtitle: 'CTY, summer 2023',
    short: 'A breadboard circuit with an LCD that ran several games, played with push buttons.',
    org: 'CTY',
    date: 'Summer 2023',
    year: '2023',
    body: [{ h: 'Overview', p: ['On a breadboard we built a circuit with an LCD display and programmed it to run several different games, with buttons to jump and play.'] }],
    media: [],
  },
  {
    slug: 'cardboard-simulator',
    kind: 'archive',
    title: 'Cardboard Racing Simulator',
    short: 'A racing sim made from cardboard, duct tape and conductive tape when I was 11.',
    org: 'Personal project',
    date: 'Mar 2020',
    year: '2020',
    body: [{ h: 'Overview', p: ['When I was 11, I made a racing simulator out of cardboard, duct tape and conductive tape, wired with alligator clips to a Makey Makey keyboard emulator.'] }],
    media: [{ v: 'videos/cardboard-simulator-demo.mp4', c: 'Demo', tall: true }],
  },
];

export const about = {
  lede: 'I design and build robots, drones and electric vehicles, from the first CAD sketch to the last wire.',
  p: [
    'I study mechanical engineering at the University of Illinois Urbana-Champaign, with a minor in electrical and computer engineering.',
    'I have been building robots since 2020: four years as an FTC team captain, a season designing an FRC robot solo, and research at MIT Lincoln Laboratory on a drone that docks onto a ground rover. I am most interested in assistive technology, AI-driven robotics and electric vehicles, and I plan to pursue entrepreneurship.',
    'At Illinois I am on Illini Electric Motorsports. On chassis I am leading the redesign of a lap-belt attachment from aluminum to composite, simulated in Ansys ACP. On circuit design I am building a data-acquisition sensor board in Altium.',
  ],
};
