// Single source of truth for every project on jerryli.design.
// Every fact here is one Jerry has stated himself. Do not add claims he has not made.
//
// kind:    main | hackathon | concept | object | archive
// draft:   true = waiting on media from Jerry's project folder. Drafts only render in
//          preview builds (PREVIEW=1) and never in production.
// media:   { v: 'videos/x.mp4' } or { i: 'images/x.jpg' }, with a caption.
// preview: hover loop in assets/previews/<slug>.mp4 (built by tools/previews.sh).

export const site = {
  name: 'Jerry Li',
  url: 'https://www.jerryli.design',
  email: 'jerry@jerryli.design',
  linkedin: 'https://www.linkedin.com/in/jerry-li-md/',
  github: 'https://github.com/jerryli08',
  description: 'Jerry Li is a mechanical engineering student at the University of Illinois Urbana-Champaign who designs and builds robots, drones and electric vehicles.',
};

export const projects = [
  // ------------------------------------------------------------------ MAIN
  {
    slug: 'hybrid-vehicle', pinned: true, hero: true, size: 'lg', // the live 3D scene on the landing page
    kind: 'main',
    title: 'Drone on Wheels',
    subtitle: 'Hybrid aerial-ground vehicle',
    short: 'A drone and a ground rover that dock together, so each one can carry the other.',
    org: 'MIT Lincoln Laboratory',
    date: 'Jul to Aug 2025',
    year: '2025',
    role: 'Project lead. Designed and fabricated all hardware',
    team: '7 people',
    tools: ['Fusion 360', '3D printing', 'Linkage design', 'Servo actuation'],
    stats: [
      { v: 'First author', l: 'Poster at IEEE MIT URTC 2025' },
      { v: '10 DOF', l: 'Latch linkage driven by one servo' },
      { v: '7', l: 'Person team' },
    ],
    body: [
      { h: 'Overview', p: [
        'I came up with this project, recruited the team, and designed and fabricated all of the hardware. It is a cooperative multi-agent system: an aerial vehicle (UAV) with custom landing gear, and a ground vehicle (UGV) with actuated latches that lock onto that gear.',
        'Docked, each vehicle can carry the other. The UGV carries the UAV to save its battery, and the UAV lifts the UGV over terrain it cannot drive across or up to an aerial viewpoint. The target applications are search and rescue and data collection.',
      ]},
      { h: 'The latch', p: [
        'The docking latch is a linkage geartrain with 10 degrees of freedom, 4 passive and 6 active, all driven by a single servo so the mechanism stays light enough to fly.',
      ]},
      { h: 'Research', p: [
        'After the summer we ran more tests, collected more data and wrote the work up. I presented the poster, "Drone on Wheels: A Hybrid UAV-UGV System for Precision Course Navigation", as co-first author at the IEEE MIT Undergraduate Research Technology Conference on October 10 to 12, 2025. SLAM integration was the next step we identified.',
        'Authors: Jerry Li and Mihika Sakharpe (co-first), Zoe Zhao, Katherine Zhang, William Kollmyer, Shashwat Pandya, and Chris Rincon (PI).',
      ]},
    ],
    media: [
      { v: 'videos/hybrid-vehicle-flight.mp4', c: 'UAV carrying the UGV' },
      { v: 'videos/hybrid-vehicle-driving.mp4', c: 'UGV carrying the UAV' },
      { v: 'videos/hybrid-vehicle-detached.mp4', c: 'Operating separately on the course' },
    ],
    links: [{ label: 'Research poster (PDF)', href: '/assets/docs/drone-on-wheels-poster.pdf' }],
    cad: 'https://a360.co/45sUzAD',
  },
  {
    slug: 'ftc-decode', featured: 2,
    kind: 'main',
    title: 'FTC DECODE Robot',
    subtitle: 'Team 26115 Alphabots',
    short: 'Captain of the team that won a 1st place award at the FIRST World Championship.',
    org: 'FIRST Tech Challenge',
    date: 'Sep 2025 to May 2026',
    year: '2026',
    role: 'Team captain',
    team: 'Alphabots, FTC 26115',
    tools: ['Turret shooter', 'Auto-tracking', 'Active intake'],
    stats: [
      { v: '1st place', l: 'Sustain Award, FIRST World Championship' },
      { v: '8,000+', l: 'FTC teams worldwide' },
      { v: '50,000+', l: 'Views on our build content' },
    ],
    body: [
      { h: 'Overview', p: [
        'I captained Alphabots through the 2025-26 DECODE season. The robot scores with an auto-tracking turret shooter, fed by an active intake and transfer.',
        'At the FIRST World Championship in May 2026 we won the 1st place Sustain Award, which recognizes building a program that outlasts its founders. Our build videos reached more than 50,000 views across Instagram, YouTube and TikTok.',
      ]},
    ],
    media: [
      { v: 'videos/ftc-decode-worlds-match.mp4', c: 'Qualification match at the World Championship. We are 26115, the dark robot on the red alliance' },
      { v: 'videos/ftc-decode-turret-tracking.mp4', c: 'Auto-tracking turret shooter' },
      { v: 'videos/ftc-decode-intake-testing.mp4', c: 'First tests of the active intake and transfer' },
    ],
  },
  {
    slug: 'frc-rebuilt', pinned: true, featured: 1,
    kind: 'main',
    title: 'FRC REBUILT Robot',
    subtitle: 'Team 2856 Planetary Drive',
    short: 'Designed solo in my first FRC season. It played in the playoffs at the Smoky Mountains Regional.',
    org: 'FIRST Robotics Competition',
    date: 'Jan to Mar 2026',
    year: '2026',
    role: 'Sole designer',
    team: 'Planetary Drive, FRC 2856',
    tools: ['Fusion 360'],
    stats: [
      { v: 'Solo', l: 'Robot design' },
      { v: '21 of 46', l: 'Qualification rank' },
      { v: 'Round 2', l: 'Playoffs, 7th alliance' },
    ],
    body: [
      { h: 'Overview', p: [
        'I designed this robot by myself for FRC team 2856, Planetary Drive, for the 2026 game REBUILT. It was my first FRC season.',
        'At the 2026 Smoky Mountains Regional the team ranked 21st of 46, was picked onto the 7th alliance, and went out in the second round of the playoffs.',
      ]},
    ],
    media: [
      { i: 'images/frc-rebuilt.jpg', c: 'The robot at the 2026 Smoky Mountains Regional' },
    ],
    cad: 'https://a360.co/4lvYOTs',
  },
  {
    slug: 'build-plate-robot', pinned: true, featured: 4,
    kind: 'main',
    title: 'Replac3d',
    subtitle: 'Automatic 3D printer build plate changer',
    short: 'A robot that swaps finished build plates for fresh ones so a 3D printer can run around the clock.',
    org: 'Personal project',
    date: 'Feb to Aug 2024',
    year: '2024',
    role: 'Solo build',
    team: 'Solo',
    tools: ['Fusion 360', 'Stepper motors', 'TMC2209', 'Arduino', 'Electromagnet'],
    stats: [
      { v: 'Top 12', l: 'of 2,042 projects, Hack Club Arcade' },
      { v: '$300', l: 'Polymaker sponsorship' },
      { v: '24 h', l: 'Printing, up from 7 h a day' },
    ],
    body: [
      { h: 'The problem', p: [
        'My FTC team could only run our 3D printer from 3 to 10 PM, because someone had to be there to pull each finished print. Replac3d removes the finished build plate, sets it aside and loads a fresh one, so the printer can keep going unattended all day and night.',
      ]},
      { h: 'How it works', p: [
        'A linear slide carries an electromagnet onto the printer\'s magnetic build plate and pulls it out, with a belt-driven stepper handling the retraction. A belt-driven turntable then swaps the full plate for an empty one. Two TMC2209 stepper drivers on a custom perfboard run everything from an Arduino Uno.',
      ]},
      { h: 'The hard part', p: [
        'Getting the electromagnet to latch onto the plate reliably. I solved it by switching to custom-made steel build plates, which made pickup 100% reliable.',
      ]},
    ],
    media: [
      { v: 'videos/replac3d-demo-4x.mp4', c: 'A full cycle at 4x speed', tall: true },
      { v: 'videos/replac3d-cncing-plates.mp4', c: 'The aluminum side plates being CNC machined' },
      { i: 'images/replac3d-mid-build.jpg', c: 'Mid-build: steppers on a CNC aluminum mount, stood off from the laser-cut steel base plate' },
      { v: 'videos/replac3d-hand-demo.mp4', c: 'Running the removal and replacement motion by hand' },
      { i: 'images/replac3d-perfboard.jpg', c: 'Custom perfboard: two TMC2209 stepper drivers on an Arduino Uno' },
      { v: 'videos/replac3d-auto-test.mp4', c: 'Automated test of the turntable and extension', tall: true },
      { v: 'videos/replac3d-drag-chain.mp4', c: 'Drag chain cable management test', tall: true },
      { i: 'images/replac3d-finished.jpg', c: 'The finished robot' },
    ],
    cad: 'https://a360.co/47cTdf9',
  },
  {
    slug: 'electric-vehicle', size: 'wide',
    kind: 'main',
    title: 'Science Olympiad Electric Vehicle',
    subtitle: '2024-25 Electric Vehicle event',
    short: 'A precision-stopping race car that took 1st at regionals and 2nd of 72 at the UPenn Invitational.',
    org: 'Science Olympiad',
    date: 'Sep 2024 to Jan 2025',
    year: '2025',
    role: 'Designed and built solo. My partner helped test',
    team: 'Solo build',
    tools: ['Fusion 360 FEA', 'G10 fiberglass', 'BLDC motor', 'MT6701 encoder', 'Arduino Nano', 'BLHeli_32'],
    stats: [
      { v: '1st of 48', l: 'East Maryland Regional' },
      { v: '2nd of 72', l: 'UPenn Invitational' },
      { v: '73%', l: 'Lighter chassis plates' },
    ],
    body: [
      { h: 'Overview', p: [
        'I designed and built this car by myself for the 2024-25 Science Olympiad Electric Vehicle event, which scores a car on how quickly it covers a set distance and how close to the target it stops. It is a 30 by 60 cm all-wheel-drive car that covered 8.3 m in 2.97 s and stopped 1.1 cm (0.13%) from the target.',
      ]},
      { h: 'Iteration', p: [
        'Version one used CNC-cut HDF plates. They were heavy, and too stiff: I knew the chassis needed to flex over floor bumps. For version two I used Fusion 360 FEA to design a lattice into 1.5 mm G10 fiberglass plates that gives the chassis torsional flexibility, so the car passively absorbs bumps in the floor.',
        'The two main plates went from 738 g to 198 g, 73% lighter, and the run time dropped from about 15 s to 2.9 s.',
      ]},
      { h: 'Electronics', p: [
        'An Arduino Nano reads an MT6701 magnetic absolute encoder over I2C and drives the brushless motor\'s ESC with PWM. The ESC is tuned in BLHeli_32 Suite.',
      ]},
      { h: 'Results', p: [
        '1st of 48 at the East Maryland Regional, 2nd of 28 at the Maryland State Championship, 2nd of 72 at the UPenn Invitational (behind the team that went on to win nationals), and 4th of 57 at the Princeton Invitational.',
      ]},
    ],
    media: [
      { v: 'videos/sciolyev-home-test.mp4', c: 'Early test at home, real time', tall: true },
      { v: 'videos/sciolyev-school-test.mp4', c: 'Testing at school', tall: true },
      { i: 'images/electric-vehicle.jpg', c: 'The finished car' },
      { v: 'videos/sciolyev-motor-test.mp4', c: 'Integrated test of the brushless motor and MT6701 encoder', tall: true },
      { v: 'videos/sciolyev-v1-test.mp4', c: 'First ground test on the HDF plates: too heavy, and the ESC was not tuned yet', tall: true },
      { i: 'images/sciolyev-v2-mid-build.jpg', c: 'Mid-rebuild with the 1.5 mm G10 fiberglass plates' },
    ],
    cad: 'https://a360.co/4o6t1bB',
  },
  {
    slug: 'electric-vehicle-2026',
    kind: 'main',
    draft: true,
    title: 'Science Olympiad Electric Vehicle 2026',
    subtitle: '2025-26 Electric Vehicle event',
    short: 'My car for the 2025-26 Science Olympiad Electric Vehicle event.',
    org: 'Science Olympiad',
    date: 'Sep 2025 to Mar 2026',
    year: '2026',
    body: [{ h: 'Overview', p: ['My car for the 2025-26 Science Olympiad Electric Vehicle event, the season after my first electric vehicle.'] }],
    links: [{ label: 'See the 2024-25 car', href: '/projects/electric-vehicle' }],
    media: [],
  },
  {
    slug: 'scioly-machines',
    kind: 'main',
    draft: true,
    title: 'Science Olympiad Machines',
    subtitle: '2025-26 Machines event',
    short: 'My build for the 2025-26 Science Olympiad Machines event.',
    org: 'Science Olympiad',
    date: 'Sep 2025 to Mar 2026',
    year: '2026',
    body: [{ h: 'Overview', p: ['My build for the 2025-26 Science Olympiad Machines event.'] }],
    media: [],
  },
  {
    slug: 'electric-bike', pinned: true, featured: 3,
    kind: 'main',
    title: 'Electric Bike',
    subtitle: '5.3 kW mid-drive conversion',
    short: 'A standard bicycle converted into a 5.3 kW mid-drive e-bike, with every custom part designed by me.',
    org: 'Personal project',
    date: 'Jun to Aug 2025',
    year: '2025',
    role: 'Solo build',
    team: 'Solo',
    tools: ['Fusion 360', 'Sheet metal design', '5052 aluminum', 'Carbon fiber', 'VESC'],
    stats: [
      { v: '5.3 kW', l: 'Mid-drive' },
      { v: '5052', l: 'Bent, powder-coated aluminum parts' },
      { v: 'Solo', l: 'Design and build' },
    ],
    body: [
      { h: 'Overview', p: [
        'I converted a standard bicycle into a 5.3 kW mid-drive electric bike. I designed all of the custom parts. Most are laser cut and bent from 5052 aluminum and powder coated, with a few CNC-cut from carbon fiber sheet or laser cut from stainless steel.',
        'Belt reductions bring the drive down to the crank, and the cranks freewheel so the pedals stay still under power. The throttle is configured in VESC Tool.',
      ]},
    ],
    media: [
      { v: 'videos/ebike-riding.mp4', c: 'Riding' },
      { v: 'videos/ebike-outside-walkaround.mp4', c: 'Walkaround' },
      { v: 'videos/ebike-close-up.mp4', c: 'Close-up on the belt reductions' },
      { i: 'images/ebike-nondrive-side.jpg', c: 'Non-drive side' },
      { v: 'videos/ebike-max-speed.mp4', c: 'Max speed test, with the cranks freewheeling' },
      { i: 'images/ebike-parts.jpg', c: 'Custom parts: bent and powder-coated 5052 aluminum, CNC carbon fiber and laser-cut stainless' },
      { i: 'images/ebike-build-progress.jpg', c: 'Mid-build: drive mounted, mocking up the first belt stage' },
      { i: 'images/ebike-vesc-config.jpg', c: 'Configuring the throttle in VESC Tool' },
    ],
    cad: 'https://a360.co/45BrfHR',
  },
  {
    slug: 'ftc-into-the-deep',
    kind: 'main',
    title: 'FTC INTO THE DEEP Robot',
    subtitle: 'Team 18996 S.T.A.T.I.C.',
    short: 'Our most successful S.T.A.T.I.C. season: 1st place Think Award at regionals and division semifinalists.',
    org: 'FIRST Tech Challenge',
    date: 'Sep 2024 to Feb 2025',
    year: '2025',
    role: 'Team captain',
    team: 'S.T.A.T.I.C., FTC 18996',
    tools: ['Fusion 360'],
    stats: [
      { v: '1st place', l: 'Think Award, FIRST Chesapeake Regionals' },
      { v: 'Semifinalist', l: 'Division playoffs' },
    ],
    body: [
      { h: 'Overview', p: [
        'The 2024-25 season was S.T.A.T.I.C.\'s most successful. We won the 1st place Think Award, which recognizes the engineering design process, at the FIRST Chesapeake Regionals, and made the division semifinals.',
      ]},
    ],
    media: [
      { v: 'videos/ftc-2025.mp4', c: 'The 2024-25 robot' },
    ],
  },
  {
    slug: 'autonomous-drone-racing',
    kind: 'main',
    draft: true,
    title: 'Autonomous Drone Racing',
    subtitle: 'Capstone race winner',
    short: 'Won the capstone autonomous drone race against four other teams.',
    org: 'MIT Department of Aeronautics and Astronautics',
    date: 'Jul to Aug 2025',
    year: '2025',
    role: 'Autonomous systems engineering intern',
    tools: ['ROS'],
    stats: [{ v: '1st place', l: 'Capstone autonomous drone race' }],
    body: [
      { h: 'Overview', p: [
        'At MIT AeroAstro I worked on autonomous drone racing using ROS. Our team won the capstone autonomous drone race against four other teams pursuing the same objective.',
      ]},
    ],
    media: [],
  },
  {
    slug: 'pen-plotter',
    kind: 'main',
    title: '5-Bar Pen Plotter',
    subtitle: 'Parallel robot with inverse kinematics',
    short: 'A 5-bar parallel robot that draws from Cartesian coordinates, built to learn the linear algebra behind robot arms.',
    org: 'Personal project',
    date: 'May to Jun 2025',
    year: '2025',
    role: 'Solo build',
    team: 'Solo',
    tools: ['Inverse kinematics', 'C++', 'Arduino Nano', 'NEMA 17', 'TMC2209'],
    stats: [
      { v: '2', l: 'NEMA 17 steppers' },
      { v: 'IK', l: 'Cartesian to joint angles' },
    ],
    body: [
      { h: 'Overview', p: [
        'I built a 5-bar pen plotter to learn how linear algebra and transformation matrices apply in robotics. The 3D-printed arms are driven by two NEMA 17 steppers, each on a TMC2209 driver, programmed in C++ on an Arduino Nano.',
        'You give it Cartesian coordinates and inverse kinematics turns them into target angles for the two motors.',
      ]},
    ],
    media: [
      { v: 'videos/pen-plotter-jerryli.mp4', c: 'Writing "Jerry Li" from Cartesian coordinates' },
      { v: 'videos/pen-plotter-square.mp4', c: 'Drawing a square' },
    ],
    cad: 'https://a360.co/46NPB1S',
  },
  {
    slug: 'steam-carnival-robot',
    kind: 'main',
    draft: true,
    title: 'STEAM Carnival Pitching Robot',
    subtitle: 'Telescoping pitching arm',
    short: 'An FTC robot with a telescoping pitching arm, built in 4 days for the HoCo STEAM Carnival.',
    org: 'Howard County Library System',
    date: 'Jul to Aug 2024',
    year: '2024',
    role: 'STEM instructor and youth peer intern',
    tools: ['Proportional control', 'Cosine feedforward'],
    stats: [{ v: '4 days', l: 'Design to working robot' }],
    body: [
      { h: 'Overview', p: [
        'As a STEM instructor at the Howard County Library System, I built an FTC robot with a telescoping pitching arm in 4 days for the HoCo STEAM Carnival. The arm runs a proportional controller with cosine feedforward. I also wrote and taught a robotics curriculum.',
      ]},
    ],
    media: [],
  },
  {
    slug: 'battlebot',
    kind: 'main',
    title: '1 lb Combat Robot',
    subtitle: 'Antweight plastic class',
    short: 'A 1 lb antweight combat robot designed and built in 4 days for MACRO\'s Ides of July event.',
    org: 'MACRO',
    date: 'Jul 2024',
    year: '2024',
    role: 'Solo build',
    team: 'Solo',
    tools: ['Fusion 360', '3D printing'],
    stats: [
      { v: '4 days', l: 'Design to competition' },
      { v: '1 lb', l: 'Antweight plastic class' },
    ],
    body: [
      { h: 'Overview', p: [
        'In 4 days I designed and built a 1 lb plastic antweight combat robot. It competed at the Ides of July event hosted by MACRO, the Maryland Area Combat Robotics Organization.',
      ]},
    ],
    media: [
      { v: 'videos/battlebot-1.mp4', c: 'Match at Ides of July' },
      { i: 'images/battlebot-weighing.jpg', c: 'Weigh-in' },
      { v: 'videos/battlebot-2.mp4', c: 'Another match' },
    ],
    cad: 'https://a360.co/3VZaphB',
  },
  {
    slug: 'powerplay-offseason',
    kind: 'main',
    draft: true,
    title: 'PowerPlay Off-Season Robot',
    subtitle: 'My first CAD-designed robot',
    short: 'The off-season robot I built after PowerPlay, and the first robot I ever designed in CAD.',
    org: 'FIRST Tech Challenge',
    date: '2023',
    year: '2023',
    team: 'S.T.A.T.I.C., FTC 18996',
    body: [
      { h: 'Overview', p: ['The first robot I designed in CAD, built in the off-season after the 2022-23 PowerPlay season.'] },
    ],
    media: [],
  },

  // ------------------------------------------------------------------ HACKATHONS
  {
    slug: 'morph', size: 'wide',
    kind: 'hackathon',
    draft: true,
    title: 'Morph',
    subtitle: 'Self-folding robot',
    short: 'A 17-DOF robot that folds itself into 150+ shapes from a text message.',
    event: 'Hack the North 2026',
    hours: '32 h',
    place: 'Top 30 of 1,000+',
    date: 'Sep 2026',
    year: '2026',
    team: 'Daniel Ganjali, Aydan Ling, Justin Rui and me',
    role: 'Built the language and control path end to end',
    tools: ['iMessage via Linq API', 'MiniLM-L6-v2', 'GPT-4o-mini', 'A* search', 'MuJoCo'],
    stats: [
      { v: 'Top 30', l: 'of 1,000+ hackers' },
      { v: '17 DOF', l: 'Reconfigurable robot' },
      { v: '150+', l: 'Shapes' },
    ],
    body: [
      { h: 'Overview', p: [
        'Morph is a 17-DOF robot that folds itself into more than 150 shapes when you text it what you want. I built the language and control path end to end: messages arrive over iMessage through the Linq API, a local MiniLM-L6-v2 classifier maps them to a shape with GPT-4o-mini as a fallback, and fold sequences are planned with A* and validated in MuJoCo.',
        'The shape library came from all 3^17 joint permutations, filtered with an LLM down to recognizable shapes.',
      ]},
    ],
    links: [{ label: 'Demo video', href: 'https://lnkd.in/gSRzEcxE' }],
    media: [],
  },
  {
    slug: 'golden-retriever', size: 'wide',
    kind: 'hackathon',
    draft: true,
    title: 'Golden Retriever',
    subtitle: 'Assistive fetch robot',
    short: 'Text it what you need and it drives over, grabs it with a learned grasp, and brings it back.',
    event: 'Corgi Hackathon, San Francisco',
    hours: '10.5 h',
    place: '2nd of 250+ teams',
    date: 'Jul 2026',
    year: '2026',
    team: 'Tarun Malarvasan, Ryker Kollmyer, Andrew Wang and me',
    tools: ['SO-101 arm', 'ACT imitation learning', 'Monocular depth', 'Path planning', 'iMessage'],
    stats: [
      { v: '2nd', l: 'of 250+ teams, 1,500 hackers' },
      { v: '10.5 h', l: 'Build time' },
    ],
    body: [
      { h: 'Overview', p: [
        'An assistive fetch robot for people with limited leg mobility. You request an object over iMessage; the robot uses monocular depth estimation and path planning to drive to it, finds it with a side-mounted webcam, and grasps it with an SO-101 arm trained with ACT imitation learning.',
      ]},
    ],
    media: [],
  },
  {
    slug: 'linqbot',
    kind: 'hackathon',
    draft: true,
    title: 'LinqBot',
    subtitle: 'Robot arm with three control modes',
    short: 'An SO-101 arm you can run autonomously, drive with your hand through AR glasses, or text.',
    event: 'YC Startup School Hackathon',
    hours: '6.5 h',
    date: 'Jul 2026',
    year: '2026',
    team: 'Team of 5',
    tools: ['SO-101 arm', 'Inverse kinematics', 'Hand tracking', 'AR glasses', 'iMessage'],
    stats: [
      { v: '6.5 h', l: 'Build time' },
      { v: '3', l: 'Control modes' },
    ],
    body: [
      { h: 'Overview', p: [
        'Built at the YC Startup School hackathon at Soma Capital. An SO-101 arm with three control modes: autonomous pick and place of a can, hand tracking from an AR-glasses webcam that drives the arm through inverse kinematics, and control over iMessage.',
      ]},
    ],
    media: [],
  },
  {
    slug: 'braille-printer',
    kind: 'hackathon',
    title: 'Braille Printer',
    subtitle: 'Low-cost gantry prototype',
    short: 'A low-cost braille printer prototype built on a 2020 extrusion gantry.',
    event: 'PennApps XXV',
    hours: '36 h',
    date: 'Sep 2024',
    year: '2024',
    team: 'Brandon Jeon, Jacob Zhang, Oliver Leung and me',
    tools: ['2020 extrusion', 'Stepper motors', 'Timing belt'],
    stats: [{ v: '36 h', l: 'Build time' }, { v: '4', l: 'Teammates' }],
    body: [
      { h: 'Overview', p: [
        'In 36 hours at PennApps XXV, my team of four built a prototype braille printer. The gantry is 2020 aluminum extrusion with stepper motors. The X axis runs on timing belt; we ran out of belt for the Y axis, so it runs on dental floss.',
      ]},
    ],
    media: [
      { v: 'videos/braille-printer.mp4', c: 'The low-cost gantry running', tall: true },
    ],
    cad: 'https://a360.co/46GrzqS',
  },

  // ------------------------------------------------------------------ CONCEPTS
  {
    slug: 'manure-drone',
    kind: 'concept',
    draft: true,
    title: 'Manure-Collecting Drone',
    short: 'A drone concept that vacuums up cow manure to cut methane emissions in cattle-farming regions.',
    org: 'Constellation Youth Energy Summit',
    date: 'Summer 2024',
    year: '2024',
    body: [{ h: 'Overview', p: ['A drone concept that vacuums up cow manure, reducing methane emissions in rural agricultural areas with a lot of cattle farming. Designed for the Constellation Youth Energy Summit in summer 2024.'] }],
    media: [],
  },
  {
    slug: 'drone-arm',
    kind: 'concept',
    draft: true,
    title: 'Drone Grabber Arm',
    short: 'A robotic arm on a drone that grabs household objects for people living in senior homes.',
    org: 'MIT Lincoln Laboratory',
    date: 'Jul 2025',
    year: '2025',
    team: 'Same team as Drone on Wheels',
    body: [{ h: 'Overview', p: ['A robotic arm mounted on a drone, designed to grab household objects for residents of senior homes. It was an early idea from the same MIT Lincoln Laboratory team that went on to build Drone on Wheels. I designed it in CAD and started building it, but we pivoted before getting far with the idea.'] }],
    links: [{ label: 'See Drone on Wheels', href: '/projects/hybrid-vehicle' }],
    media: [],
  },
  {
    slug: 'ftc-decode-two-sided',
    kind: 'concept',
    draft: true,
    title: 'FTC DECODE Two-Sided Intake',
    subtitle: 'Robot concept for the 2025-26 DECODE game',
    short: 'An FTC DECODE robot concept that intakes from both sides, three balls wide on either side.',
    org: 'FIRST Tech Challenge',
    date: '',
    year: '',
    body: [{ h: 'Overview', p: ['A robot concept for the 2025-26 FTC DECODE game that can intake from either side of the robot, three balls wide on each side.'] }],
    links: [{ label: 'See the FTC DECODE robot', href: '/projects/ftc-decode' }],
    media: [],
  },
  {
    slug: 'vtol-tailsitter',
    kind: 'concept',
    draft: true,
    title: 'VTOL Tailsitter',
    subtitle: 'Designed in SolidWorks',
    short: 'A tailsitter VTOL aircraft I designed to learn SolidWorks, based on an MIT tailsitter.',
    org: 'Concept',
    date: '',
    year: '',
    body: [{ h: 'Overview', p: ['I designed this tailsitter to learn SolidWorks. It is based on a tailsitter aircraft from MIT.'] }],
    links: [{ label: 'The MIT tailsitter', href: 'https://news.mit.edu/2023/planning-algorithm-tailsitter-aircraft-0823' }],
    media: [],
  },
  {
    slug: 'cryptic-extendo',
    kind: 'concept',
    draft: true,
    title: 'Horizontal Extension Intake for Cryptic',
    subtitle: 'FTC CENTERSTAGE, 2023-24',
    short: 'A horizontal extension intake I designed for team Cryptic after they advanced to Worlds.',
    org: 'FIRST Tech Challenge',
    date: '2024',
    year: '2024',
    body: [{ h: 'Overview', p: [
      'After my FTC season ended and Cryptic advanced to the World Championship, I proposed a horizontal extension intake for them, since it was a clear edge that year, and designed it.',
      'They did not use it: they chose to improve other parts of their robot, mainly its reliability.',
    ] }],
    media: [],
  },
  {
    slug: 'ftc-field-cnc',
    kind: 'concept',
    draft: true,
    title: 'Upcycled CNC Router',
    short: 'A CNC router framed from the aluminum extrusion of past seasons\' FTC fields.',
    org: 'Concept',
    date: '',
    year: '',
    body: [{ h: 'Overview', p: ['A CNC router design whose frame is built from the aluminum extrusion of FTC fields from previous seasons.'] }],
    media: [],
  },

  // ------------------------------------------------------------------ 3D MODELS
  { slug: 'voronoi-face', kind: 'object', draft: true, title: 'Voronoi Face', short: 'A face sculpted as a Voronoi lattice.', year: '', media: [] },
  { slug: 'hex-napkin-holder', kind: 'object', draft: true, title: 'Hexagonal Napkin Holder', short: 'A 3D-printed hexagonal napkin holder.', year: '', media: [] },

  // ------------------------------------------------------------------ ARCHIVE
  {
    slug: 'ftc-centerstage',
    kind: 'main',
    title: 'FTC CENTERSTAGE Robot',
    short: 'Our first season with CAD. I was overly ambitious and the robot was only ready for the last event.',
    org: 'S.T.A.T.I.C., FTC 18996',
    date: 'Sep 2023 to Feb 2024',
    year: '2024',
    body: [{ h: 'Overview', p: ['The 2023-24 season was our first with CAD. I was overly ambitious with the design, so the robot was only finished in time for the last competition of the year.'] }],
    media: [{ v: 'videos/ftc-2024.mp4', c: 'The 2023-24 robot', tall: true }],
  },
  {
    slug: 'ftc-powerplay',
    kind: 'archive',
    title: 'FTC POWERPLAY Robot',
    short: 'My first season as captain, and the team\'s first time advancing to regionals.',
    org: 'S.T.A.T.I.C., FTC 18996',
    date: 'Sep 2022 to Feb 2023',
    year: '2023',
    body: [{ h: 'Overview', p: ['2022-23 was my first season as captain and our first year advancing to regionals.'] }],
    media: [{ v: 'videos/ftc-2023.mp4', c: 'The 2022-23 robot' }],
  },
  {
    slug: 'robot-tour',
    kind: 'main',
    title: 'Science Olympiad Robot Tour',
    short: 'A navigation robot on an optical flow sensor, and a lesson in accumulated drift.',
    org: 'Science Olympiad',
    date: 'Dec 2024 to Apr 2025',
    year: '2025',
    body: [{ h: 'Overview', p: [
      'I built this robot by myself for the 2024-25 Science Olympiad Robot Tour event.',
      'It navigated with an optical flow sensor, which was not accurate enough: it drifted over time, and the accumulated error pulled the robot\'s position estimate away from where it actually was.',
    ] }],
    media: [{ v: 'videos/robot-tour.mp4', c: 'Robot Tour navigation run', tall: true }],
    cad: 'https://a360.co/4pWI35v',
  },
  {
    slug: 'mt-shirt',
    kind: 'main',
    title: 'Monkeytype Shirt',
    short: 'A shirt I designed for Monkeytype, sold on their official store.',
    org: 'Monkeytype',
    date: 'May to Jun 2025',
    year: '2025',
    body: [{ h: 'Overview', p: ['I designed a shirt for Monkeytype, a typing test website with more than 13 million visits a month. It is sold on the official Monkeytype store.'] }],
    media: [
      { i: 'images/mt-shirt.jpg', c: 'The shirt' },
      { i: 'images/mt-shirt-store.jpg', c: 'On the Monkeytype store' },
    ],
    links: [{ label: 'Monkeytype store', href: 'https://monkeytype.store/products/deconstructed-t-shirt-printed' }],
    cad: 'https://a360.co/3Lh6xqg',
  },
  {
    slug: 'bike-odometer',
    kind: 'main',
    title: 'Exercise Bike Odometer',
    short: 'An odometer for my family\'s stationary bike, built in a 12-hour, one-day challenge.',
    org: 'Personal project',
    date: 'Jun 2025',
    year: '2025',
    body: [{ h: 'Overview', p: ['I made an odometer for my family\'s stationary bike. To challenge myself I gave myself one day, and finished in 12 hours.'] }],
    media: [{ v: 'videos/bike-odometer.mp4', c: 'Demo' }],
    cad: 'https://a360.co/4gWhdq9',
  },
  {
    slug: 'ftc-freight-frenzy',
    kind: 'archive',
    title: 'FTC FREIGHT FRENZY Robot',
    short: 'The 2021-22 robot. It was not finished in time to compete.',
    org: 'S.T.A.T.I.C., FTC 18996',
    date: 'Sep 2021 to Jan 2022',
    year: '2022',
    body: [{ h: 'Overview', p: ['The 2021-22 robot. Unfortunately it was not finished in time, so we did not compete that season.'] }],
    media: [{ v: 'videos/ftc-2022.mp4', c: 'The 2021-22 robot' }],
  },
  {
    slug: 'ftc-ultimate-goal',
    kind: 'archive',
    title: 'FTC ULTIMATE GOAL Robot',
    short: 'My first FTC season. I was the team\'s only programmer.',
    org: 'S.T.A.T.I.C., FTC 18996',
    date: 'Sep 2020 to Jan 2021',
    year: '2021',
    body: [{ h: 'Overview', p: ['2020-21 was my first year in FTC, and I was the only programmer on the team.'] }],
    media: [{ v: 'videos/ftc-2021.mp4', c: 'The 2020-21 robot' }],
  },
  {
    slug: 'cty-2023',
    kind: 'archive',
    draft: true,
    title: 'Breadboard Game Console',
    subtitle: 'CTY, summer 2023',
    short: 'A breadboard circuit with an LCD that ran several games, played with push buttons.',
    org: 'CTY',
    date: 'Summer 2023',
    year: '2023',
    body: [{ h: 'Overview', p: ['On a breadboard we built a circuit with an LCD display and programmed it to run several different games, with buttons to jump and play.'] }],
    media: [],
  },
  {
    slug: 'cardboard-simulator',
    kind: 'archive',
    title: 'Cardboard Racing Simulator',
    short: 'A racing sim made from cardboard, duct tape and conductive tape when I was 11.',
    org: 'Personal project',
    date: 'Mar 2020',
    year: '2020',
    body: [{ h: 'Overview', p: ['When I was 11, I made a racing simulator out of cardboard, duct tape and conductive tape, wired with alligator clips to a Makey Makey keyboard emulator.'] }],
    media: [{ v: 'videos/cardboard-simulator-demo.mp4', c: 'Demo', tall: true }],
  },
];

export const about = {
  lede: 'I design and build robots, drones and electric vehicles, from the first CAD sketch to the last wire.',
  p: [
    'I study mechanical engineering at the University of Illinois Urbana-Champaign, with a minor in electrical and computer engineering.',
    'I have been building robots since 2020: four years as an FTC team captain, a season designing an FRC robot solo, and research at MIT Lincoln Laboratory on a drone that docks onto a ground rover. I am most interested in assistive technology, AI-driven robotics and electric vehicles, and I plan to pursue entrepreneurship.',
    'At Illinois I am on Illini Electric Motorsports. On chassis I am leading the redesign of a lap-belt attachment from aluminum to composite, simulated in Ansys ACP. On circuit design I am building a data-acquisition sensor board in Altium.',
  ],
};
